### ISSUE TITLE
400 Bad Request when submitting via AJAX

### ISSUE THREAD

**Issue by auralon** [craftcms/contact-form#102]
At present the [v1] ContactFormController requires a **POST** request, but the provided `$.ajax` method in the README uses the default **GET** method, that triggers a 400 error.

**Comment by auralon** [comment]
I've just noticed that the v1 README uses `$.post`, so this is only an issue when someone uses the v1 plugin and the v2 ajax instructions!   I haven't tested it with v2, but it looks like the SendController requires **POST** too, so I'll leave this open until someone can confirm that it isn't an issue.

**Comment by brandonkelly** [comment]
Thanks for the heads up! Fixed the v2 readme :)

**Comment by arthurdewolf** [comment]
I still think that there is a problem with the Ajax example in the README for Craft 3. I was getting the "400 Bad Request" error when using the `$.post` example. When I changed it to `$.ajax` and added `method: 'POST'` it worked. The syntax for `$.post` is different (`$.post(URL,data,callback);`).

**Comment by brandonkelly** [comment]
@arthurdewolf You’re right - thanks for pointing that out! Really fixed now.

**Comment by timbertens** [comment]
it believe the issue in the documentation is back
it should be
```
    // Send it to the server
    $.ajax({
        method: 'POST',
        ...
```

**Comment by brandonkelly** [comment]
@timbertens jQuery’s, `$.post()` is a shortcut for `$.ajax({ method: 'post' })`.
