### ISSUE TITLE
Craft RC1 error on local dev machine (windows)

### ISSUE THREAD

**Issue by RickKukiela** [craftcms/contact-form#106]
![image](https://user-images.githubusercontent.com/3813238/33629012-33b3b622-d9c8-11e7-82f5-564401648df8.png)

When I submit the form I get this. 

I have tried running papercut and fakeSMTP as my local MTA  - They both work in my other applications.

I have pushed this to the server and it runs fine so I'm not sure what to do to get this to work on my dev box.

**Comment by brandonkelly** [comment]
> I have pushed this to the server and it runs fine so I'm not sure what to do to get this to work on my dev box.

Do you have different email settings in dev vs. production?

**Comment by RickKukiela** [comment]
no my database is literally dumped and included with pushes and pulls so the db would be identical in both environments. I also checked my config files and there is nothing there related to email.

I found this on stack exchange: https://stackoverflow.com/questions/17484057/how-can-i-use-fake-sendmail-with-swiftmailer-on-windows

I havent checked the code but as per the suggestion maybe we need to do: Swift_MailTransport instead of Swift_SendmailTransport (not sure which we're using)

I do not have a sendmail.exe installed as suggested but I have never needed it in the past as long as I'm running papercut or fakeSMTP at runtime.

They are both port based not file socket based so it looks like swift is trying to force the process / cli way of sending mail instead of doing it via the tcp socket.

**Comment by takobell** [comment]
[Swiftmailer 6](https://github.com/swiftmailer/swiftmailer) removed support for [PHP mail](https://secure.php.net/manual/en/function.mail.php) (the `Swift_MailTransport` class), so Craft dropped it as a mail transport option and uses sendmail by default now.  Guessing that's what you're running into.

**Comment by RickKukiela** [comment]
@takobell I'm not following here exactly... If they dropped mail() support then wouldn't SMTP socket be the only way to send the mail? I don't see any configuration opts for setting up a send mail account and password etc. On this particular site we have not entered in any smtp configuration for any mail so so I don't see how this could work on the server if it dropped support for `mail()` yet for some reason it still works on the server. The only possibility at that point would be that its basically bypassing `mail()` and `exec-ing` the `sendmail` script from shell... 

Is there a way to to just tell contact-form mailer to use SMTP instead? That way I can have this working locally and on the server? you know, since I dont have a sendmail.exe file on my system...

**Comment by takobell** [comment]
Contact Form is just going to use whatever email transport is set under Settings->Email in the Control Panel.

![capture](https://user-images.githubusercontent.com/61869/34133570-566c5038-e40a-11e7-8a07-06913fdc3adb.PNG)

sendmail, GMail and SMTP are all native options, with sendmail being the default. You can change it to whatever you want or use a plugin that adds another transport option like:

https://github.com/craftcms/mailgun

https://github.com/flipboxfactory/craft-postmark

If it was working before and isn't now, then you probably installed Craft 3 from an earlier build that still had PHP mail support and updated to a latter one that doesn't.  PHP mail is still probably saved as the email transport setting in the database.  Re-saving your email settings will overwrite it.

**Comment by RickKukiela** [comment]
Thanks for that. Just need to look up how to override those settings per environment since I want to use sendmail on the server but not on my local machine :)
