### ISSUE TITLE
Multiple forms on one page honeypot ID

### ISSUE THREAD

**Issue by kevadamson** [craftcms/contact-form#107]
Is there a way to have multiple forms on one page with different honeypot IDs? Obviously I can't have the same ID on every form.

**Comment by brandonkelly** [comment]
@kevadamson Are you asking for Craft 2 or Craft 3?

**Comment by kevadamson** [comment]
2. Am I right in that it is targeted by the name and not the ID? If so it makes my initial question void I guess?

**Comment by brandonkelly** [comment]
Right, the name is all that matters from the back-end’s perspective.
