### ISSUE TITLE
Error when trying to send form with checkbox fields

### ISSUE THREAD

**Issue by KevinAllen4325** [craftcms/contact-form#111]
I followed the guide and after submitting the form i get this error 

> strip_tags() expects parameter 1 to be string, array given

`		<p>Area of Interest:</p>
`
`		<label><input type="checkbox" name="message[Services][]" value="Roofing">Roofing</label>
`
`		<label><input type="checkbox" name="message[Services][]" value="Siding">Siding</label>
`
`		<label><input type="checkbox" name="message[Services][]" value="Gutters">Gutters</label>
`
`		<label><input type="checkbox" name="message[Services][]" value="Windows">Windows</label>
`

using v1 on craft 2.x

**Comment by angrybrad** [comment]
Can you enable [devMode](https://craftcms.com/docs/config-settings#devMode) and share the full stack trace leading up to that error?

**Comment by KevinAllen4325** [comment]
![stack](https://user-images.githubusercontent.com/26398311/34886043-7e30634e-f787-11e7-8a3f-1bc6a86db194.jpg)

**Comment by angrybrad** [comment]
You've got a "Contact Form HTML" plugin installed that's listening to our `onBeforeMessageCompile` event that the error is coming from.
