### ISSUE TITLE
Errors no longer shown, since Craft RC13

### ISSUE THREAD

**Issue by nternetinspired** [craftcms/contact-form#117]
I recently implemented a simple contact page, essentially identical to the basic example in https://github.com/craftcms/contact-form#usage but with the addition of flash messages; https://github.com/craftcms/contact-form#displaying-flash-messages

It worked perfectly, and as expected, until I updated Craft to RC13. Now the form fails silently, no flash message and no form errors. Any idea what's happened and how I can fix it? TIA.

**Comment by MakeilaLundy** [comment]
Hey @nternetinspired, 
I am running RC17.1 and I cannot reproduce the error using the exact template code for the main body and the flash messages. It seems to work as intended.  Try updating to the newest version, and if you are still experiencing this issue let us know.
