### ISSUE TITLE
Empty field causes «Calling unknown method» error

### ISSUE THREAD

**Issue by kaspar-allenbach** [craftcms/contact-form#123]
I use the standard markup template 1:1.

The form works. But when I leave a field empty this is the error:

> Calling unknown method: craft\contactform\models\Submission::summit() at line 3

```
<label class="form__label" for="summit">Summit</label>
    <input id="summit" type="text" name="message[summit]" value="{{ message.summit ?? '' }}">
{{ message is defined and message ? errorList(message.getErrors('summit')) }}
```

**Comment by MakeilaLundy** [comment]
Hi Kaspar, 
I am unable to reproduce your issue with just this snippet of code placed within the standard template. Could you send over your entire template? 

Thanks, Makeila

**Comment by kaspar-allenbach** [comment]
Here is the form:
[organismForm.twig.zip](https://github.com/craftcms/contact-form/files/1897948/organismForm.twig.zip)

**Comment by MakeilaLundy** [comment]
Hello again @kaspar-allenbach,
The documentation for [adding additional fields](https://github.com/craftcms/contact-form#adding-additional-fields) was incorrect. For your fields using the array syntax such as message[summit], your value for the field should look like this:
`value="{{ message.messge.summit ?? '' }}" `

Thanks for bringing this to our attention, we will fix the documentation to show the correct syntax,
Makeila
