### ISSUE TITLE
Hashed values in hidden inputs (e.g. for toEmail) still have the unhashed value at the end of the string

### ISSUE THREAD

**Issue by thisisjamessmith** [craftcms/contact-form#132]
This strikes me as a bit odd. Sure, it allows for validation of the data and prevents tampering, but the other half of the point of hashing the data is obfuscation.

**Comment by angrybrad** [comment]
Hashing is a one-way operation. You can't get the original value back from it, hence the need to append the original string to the end to ensure it wasn't tampered with.  

You're probably thinking of encrypting/decrypting, which is a different beast.
