### ISSUE TITLE
fromName / fromEmail vs. Name and Email

### ISSUE THREAD

**Issue by thisisjamessmith** [craftcms/contact-form#133]
I don't understand why these fields are duplicated in the notification email? Anyway to get rid of one set?

**Comment by angrybrad** [comment]
You can write a little plugin that listens to the [beforeSend](https://github.com/craftcms/contact-form#the-beforesend-event) event and modify the body of the email however you like.

**Comment by thisisjamessmith** [comment]
Sorry for the delay getting back to you. I've tested again and the problem is no longer there. At some point Craft was upgraded and maybe that cured the issue.

**Comment by brandonkelly** [comment]
Thanks for the update!
