### ISSUE TITLE
Cannot update frontend settings when additional emails are set via toEmail field

### ISSUE THREAD

**Issue by SteadfastCollective** [craftcms/contact-form#137]
When adding a custom toEmail override in the config and in the form inputs as demonstrated here: https://github.com/craftcms/contact-form#dynamically-adding-email-recipients the frontend interface will not allow the default email to be set as shown here:

<img width="2048" alt="screen shot 2018-07-04 at 10 35 14" src="https://user-images.githubusercontent.com/39373080/42269472-22935128-7f76-11e8-9578-984b3e358cdd.png">

**Comment by brandonkelly** [comment]
This was a documentation bug. Just updated the example in the docs to something that will work more  reliably in Craft 3: https://github.com/craftcms/contact-form#dynamically-adding-email-recipients
