### ISSUE TITLE
Page HTML emailed via AJAX

### ISSUE THREAD

**Issue by Moorst** [craftcms/contact-form#140]
I'm attempting to submit via AJAX, but the email is being sent with the HTML of my home page.
 
The response is successful; 
`{"success":true}`

and the form data submitted in the headers seems to be fine (trimmed the CSRF);

`CRAFT_CSRF_TOKEN: BdD-QFmpo...
message[type][]: Private event
fromEmail: test@gmail.com
message[body]: lorem ipsum
action: contact-form/send`

Here's the AJAX code;

```
var data = $('#form').serialize();
$.post({
    url: '/',
    dataType: 'json',
    data: data,
    success: function(response) {
        if (response.success) {
            console.log(response.success);
        } else {
            console.log(response.error);
        }
    }
});
```

and the form;

```
<form id="form" method="post" action="" accept-charset="UTF-8">

    {{ csrfInput() }}

    <label>Event type</label>
    
    <div class="radio">
        <input type="radio" name="message[type][]" id="enquiry-type-private-event" value="Private event">	
        <label for="enquiry-type-private-event">Private event</label>
    </div>

    <div class="radio">
        <input type="radio" name="message[type][]" id="enquiry-type-corporate-event" value="Corporate event">
        <label for="enquiry-type-corporate-event">Corporate event</label>
    </div>

    <div class="radio">
        <input type="radio" name="message[type][]" id="enquiry-type-other" value="Other">
        <label for="enquiry-type-other">Other</label>
    </div>

    <label for="enquiry-email">Your email address</label>
    <input type="email" name="fromEmail" id="enquiry-email" required>
    
    <label for="enquiry-message">Event details</label>
    <textarea name="message[body]" id="enquiry-message"></textarea>
    			
    <input type="hidden" name="action" value="contact-form/send">

    <button type="submit" class="btn btn--primary">Submit</button>

</form>
```

When trying to debug this, I copied the example form from the docs and posted normally. This also caused a problem, sending me to /[object%20HTMLInputElement]. The redirect url appeared as `<input type="hidden" name="redirect" value="65ec3f7c0a5b6daf744724044f117d106e7ebaafb1b1ca1a62150580618df82dcontact/thanks">` in the HTML, which looked a bit odd.

I'm using 3.0.18 Craft and 2.2.2 Contact Form. I also have the 1.0.9 Contact Form Extensions plugin active.

**Comment by brandonkelly** [comment]
> I also have the 1.0.9 Contact Form Extensions plugin active.

Can you try disabling/uninstalling that and see if things go back to normal?

**Comment by Moorst** [comment]
That's solved it, feel silly for not trying that sooner now!

I'll get in touch with the developer to let them know the issue lies with their plugin.

Thanks Brandon.

**Comment by brandonkelly** [comment]
Glad that’s all it was :)
