### ISSUE TITLE
fromEmail failed validation - No Error

### ISSUE THREAD

**Issue by schellenbergk** [craftcms/contact-form#145]
Hi Guys,

If an incorrect email is entered in the input field such as `test@test` the browser validation accepts it but the form does not get sent.  In the logs I get:

```[warning] [application] Craft\ContactFormModel->fromEmail failed validation: Your Email is not a valid email address.```

but the form error is not shown when using: 
```
{% macro errorList(errors) %}
              {% if errors %}
                  <ul class="errors">
                      {% for error in errors %}
                          <li>{{ error }}</li>
                      {% endfor %}
                  </ul>
              {% endif %}
          {% endmacro %}
```

**Comment by luke-nehemedia** [comment]
Same here. An Exception is thrown and the script breaks.

**Comment by bgarrant** [comment]
Same here. Any fix?

**Comment by bgarrant** [comment]
How do we get this fix Brad? Will it just be in the next release or should we mod the files? Thank so much for fixing.
