### ISSUE TITLE
A lot of spam although honeypot in use

### ISSUE THREAD

**Issue by olsp** [craftcms/contact-form#147]
We get a lot of spam messages although we have the plugin for the honeypot in use.
What would you recommend to filter this messages? Is there a chance to implement content filters or other additional measures?

**Comment by angrybrad** [comment]
Honeypot only blocks the most basic SPAM bots, unfortunately.  You might want to looks at something like https://github.com/matt-west/craft-recaptcha or https://github.com/putyourlightson/craft-snaptcha both in the Plugin Store.
