### ISSUE TITLE
Event EVENT_AFTER_VALIDATE does not get fired

### ISSUE THREAD

**Issue by joerooster** [craftcms/contact-form#148]
The [documentation](https://github.com/craftcms/contact-form#the-aftervalidate-event) states that there's an EVENT_AFTER_VALIDATE (afterValidate) event that gets fired after validation

> Modules and plugins can be notified when a submission is being validated, providing their own custom validation logic, using the afterValidate event on the Submission model:

 but I didn't manage to find it in the code, it seems to me that it doesn't get fired. I only found [EVENT_BEFORE_SEND](https://github.com/craftcms/contact-form/blob/431a2c298480cd9253b7fc1c4198fd63620e2c5c/src/Mailer.php#L25) `$this->trigger(self::EVENT_BEFORE_SEND, $event);` and [EVENT_AFTER_SEND](https://github.com/craftcms/contact-form/blob/431a2c298480cd9253b7fc1c4198fd63620e2c5c/src/Mailer.php#L30) `$this->trigger(self::EVENT_AFTER_SEND, new SendEvent([` events. Is it correct? And if so can I PR a trigger for EVENT_AFTER_VALIDATE and EVENT_BEFORE_VALIDATE event?

**Comment by angrybrad** [comment]
Well... that's awkward. Yeah if you want to submit a PR we'll review it and get it in.

**Comment by joerooster** [comment]
@angrybrad I'm sorry, after further investigation I confirm that the event gets fired correctly, I had a problem with the custom plugin I was developing.
