### ISSUE TITLE
Give access to Contact Form settings

### ISSUE THREAD

**Issue by Pinchcliffe** [craftcms/contact-form#151]
I have a group of users that should have access to the Contact Form plugin settings. Since they do not have access to the Settings page, since they are not administrators they are not able to change the "To Email" address. Is there something I've just missed out completely, or is it impossible for them to get to this page? I don't see no harm in letting them gain access to these settings.

**Comment by angrybrad** [comment]
Currently Craft requires administrator access for anything under the Settings page in the Control Panel.

Not sure if it'd help in your case, but you can dynamically add "to" recipients via https://github.com/craftcms/contact-form#dynamically-adding-email-recipients
