### ISSUE TITLE
On form submission redirects to index.twig

### ISSUE THREAD

**Issue by satcreative** [craftcms/contact-form#156]
I have a simple contact form setup 

https://dev-craft3-bfbede7e8987.hyperlane.co/services/adviser-services

                {% if craft.app.session.hasFlash('notice') %}
		    <p class="form__notice">{{ craft.app.session.getFlash('notice') }}</p>
		{% elseif craft.app.session.hasFlash('error') %}
		    <p class="form__error">{{ craft.app.session.getFlash('error') }}</p>
		{% endif %}
		
		<form method="post" action="" accept-charset="UTF-8">
			{{ csrfInput() }}
			{{ redirectInput('thanks') }}
			<input type="hidden" name="action" value="contact-form/send">
			<input id="secretHoneypotParamName" name="honeypot" type="hidden">
			<input type="hidden" name="subject" value="{{ entry.title }}"/>
			<input type="hidden" name="message[Enquiry]" value="{{ entry.title }}"/>
			<input type="hidden" name="message[template]" value="{{ 'enquiry'|hash }}">
			<div class="form__group">
				<div class="form__row">
					<div class="form__col">
						<div class="form__field form__field--input">
							<input type="text" name="fromName" placeholder="Name*" autocomplete="name" value="{{ message.fromName ?? '' }}" required/>
						</div>
						<div class="form__field form__field--input">
					    	<input type="email" name="fromEmail" placeholder="Email address*" autocomplete="email" value="{{ message.fromEmail ?? '' }}" required/>
	
						</div>
						<div class="form__field form__field--input">
					    	<input type="tel" name="message[Phone]" placeholder="Phone number" autocomplete="tel" value="{{ message.message.phone ?? '' }}"/>
						</div>
					</div>
					<div class="form__col">
						<div class="form__field form__field--textarea form__field--textarea--3">
					    	<textarea name="message[Message]" placeholder="Message (optional)">{{ message.message.message ?? '' }}</textarea>
						</div>
					</div>
				</div>
			</div>
			<div class="form__group">
				<label class="form__check">
					<input id="GDPR-confirm" type="checkbox" name="check"/>
					<span class="form__check-box"></span> Please confirm you're happy for the information submitted in this form, to be stored and used to contact you for business purposes.
				</label>
				{{ craft.contactFormExtensions.recaptcha | raw }}
				<p class="form__sm">Form protected by Google recaptcha.</p>
			</div>
			<div class="form__group">
				<input class="form__button form__button--submit" type="submit" value="Submit"/>
			</div>
		</form>`

However, on submission, I am redirected to the index.twig template (rather than the thanks template, as defined), which results in a variable 'entry' error.

![screenshot 2019-02-07 at 11 51 17](https://user-images.githubusercontent.com/12640985/52409989-f4c9b480-2ace-11e9-83de-312c6f1fd297.png)

This seems to be an environmental issue as the form submissions resolve correctly in my local environment.

My live dev environment is setup on a Hyperlane server. The setup was working, however I got the following error: SQLSTATE[HY000]: General error: 145 Table './craft/craft_searchindex' is marked as crashed and should be repaired The SQL being executed was: SHOW FULL COLUMNS FROM `craft_searchindex`, which I resolved by executing 'REPAIR TABLE craft_searchindex;' in MyPhpAdmin. After which I began experiencing the above problems.

Has anyone else run into this problem or have any ideas?

Thanks

**Comment by angrybrad** [comment]
My guess is you're getting a validation error submitting the form and your template doesn't have any code to display what error is occurring.  See: https://github.com/craftcms/guest-entries#usage
