### ISSUE TITLE
Craft broken after trying to install plugin

### ISSUE THREAD

**Issue by piotrpog** [craftcms/contact-form#157]
I'm not sure if it is an issue with plugin specifically, or Craft itself.
When i tried to install plugin trough plugin store, it showed usual message about installing, but later when i try to access plugin list in settings, error shows up:

```
No plugin exists with the handle "contact-form".
```

Plugin store itself wont longer load and shows error: 
```
The Plugin Store is not available, please try again later.
```

Using browser devtools, under "network" tab i see that some ajax requests are returning arrors, with message symilar to mentioned earlier:

```
{"error":"No plugin exists with the handle \"contact-form\"."}
```

Craft install that got broken was only one I used for testing things, so nothing bad really happened.

Here are links to composer files:
https://pastebin.com/ZKc109wu
https://pastebin.com/xjLNTw00

**Comment by watarutmnh** [comment]
I have same issue too

**Comment by angrybrad** [comment]
FFR, this can be solved by running `craft project-config/rebuild` from the project root.
