### ISSUE TITLE
Failing to submit in MS Esge via ajax

### ISSUE THREAD

**Issue by magicspon** [craftcms/contact-form#159]
Hello,

I am trying to post my form data with ajax.

Here is my code.

```javascript

const data = new FormData(formNode)

fetch('/', {
	method: 'POST',
	body: new URLSearchParams(data)
}).then((resp) => {
   // ... 
})

```

this is working in Firefox, Chrome, and Safari.

However, Edge (latest) is throwing a hissy-fit.

i'm getting the following error in the console:

```
HTTP400: BAD REQUEST - The request could not be processed by the server due to invalid syntax.
(Fetch)POST - https://truespeed.mrbandfriends-staging.co.uk/
```

and the response body (from the network tab)

```
yii\web\BadRequestHttpException: Unable to verify your data submission.in MY_DIR/vendor/yiisoft/yii2/web/Controller.php:166
Stack trace:
MY_DIR/vendor/craftcms/cms/src/web/Controller.php(88): yii\web\Controller-&gt;beforeAction(Object(yii\base\InlineAction))
MY_DIR/vendor/craftcms/cms/src/controllers/TemplatesController.php(55): craft\web\Controller-&gt;beforeAction(Object(yii\base\InlineAction))
MY_DIR/vendor/yiisoft/yii2/base/Controller.php(155): craft\controllers\TemplatesController-&gt;beforeAction(Object(yii\base\InlineAction))
MY_DIR/vendor/craftcms/cms/src/web/Controller.php(109): yii\base\Controller-&gt;runAction(&#039;render&#039;, Array)
MY_DIR/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller-&gt;runAction(&#039;render&#039;, Array)
MY_DIR/vendor/craftcms/cms/src/web/Application.php(297): yii\base\Module-&gt;runAction(&#039;templates/rende...&#039;, Array)
MY_DIR/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application-&gt;runAction(&#039;templates/rende...&#039;, Array)
MY_DIR/vendor/craftcms/cms/src/web/Application.php(286): yii\web\Application-&gt;handleRequest(Object(craft\web\Request))
MY_DIR/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application-&gt;handleRequest(Object(craft\web\Request))
MY_DIR/public/index.php(35): yii\base\Application-&gt;run()
```

My form contains the following fields (if this is of use)
fromName, fromEmail, message[Content], message[Subject], message[Signup] and message[Phone]

Any thoughts what might be causing this issue?

**Comment by icreatestuff** [comment]
@magicspon I'm curious how you're getting this to work in Chrome. Using fetch isn't playing ball for me at all. All I seem to get back in the response is the HTML content of the homepage. In my form HTML I am including 
`<input type="hidden" name="action" value="contact-form/send">`
which I assumed would trigger the relevant controller method in the plugin, but's it's like it's getting bypassed entirely.

**Comment by magicspon** [comment]
have you included `{{ csrfInput() }}` ?

**Comment by icreatestuff** [comment]
Here's what I have

`
<form method="post" action="" accept-charset="UTF-8" class="contact-form">
                {{ csrfInput() }}

                <input type="hidden" name="action" value="contact-form/send">

                <fieldset>
                    <div class="form-field">
                        <input id="from-name" type="text" name="fromName" value="{{ message.fromName ?? '' }}" placeholder="Your Name">
                        {{ message is defined and message ? errorList(message.getErrors('fromName')) }}
                    </div>

                    <div class="form-field">
                        <input id="from-email" type="email" name="fromEmail" value="{{ message.fromEmail ?? '' }}"  placeholder="Your Email Address">
                        {{ message is defined and message ? errorList(message.getErrors('fromEmail')) }}
                    </div>
                </fieldset>

                <fieldset>
                    <div class="form-field">
                        <input id="subject" type="text" name="subject" value="{{ message.subject ?? '' }}"  placeholder="Subject">
                        {{ message is defined and message ? errorList(message.getErrors('subject')) }}
                    </div>
                </fieldset>

                <div class="form-field">
                    <textarea rows="10" cols="40" id="message" name="message" placeholder="Message...">{{ message.message ?? '' }}</textarea>
                    {{ message is defined and message ? errorList(message.getErrors('message')) }}
                </div>

                <button type="submit" class="btn btn--lblue form-submit">
                    Send Message
                </button>
            </form>
`

Doing a regular submission without AJAX works fine.

**Comment by magicspon** [comment]
hmm, not sure... i'd remove the action from the form element, might be causing conflicts with the hidden action input

**Comment by eivindml** [comment]
Did you figure this out? Trying to do this without Jquery and have the same issue.

**Comment by icreatestuff** [comment]
@eivindml Not 100%. I've got it successfully sending the email when all the required fields are fill in but if there's anything missing I'm not getting any response back (JSON) with details of which field(s) are erroring.

My JS so far...

```javascript
// On form Submission send over AJAX request
    if (window.fetch) {
        const contactForm = document.querySelector('.js-contact-form');

        contactForm.addEventListener('submit', e => {
            e.preventDefault();

            // Send form data for processing
            const formData = new FormData(contactForm),
                serializedData = Array.from(formData, x =>
                    x.map(encodeURIComponent).join('=')
                ).join('&');

            // Make post request
            fetch('/', {
                method: 'POST',
                body: new URLSearchParams(formData),
            })
                .then(response => {
                    if (response.ok) {
                        // Success, show user message
                    } else {
                        // Error, show user errors
                    }

                    return response.json();
                })
                .then(data => {
                    console.log(data);
                })
                .catch(error => {
                    console.error(error);
                });
        });
    }
```

**Comment by angrybrad** [comment]
@magicspon your original error indicates that you're not passing in the CSRF token in the post request: https://craftcms.com/guides/enabling-csrf-protection#updating-your-javascript

@icreatestuff Tested your code on this Edge version:

Microsoft Edge 44.18908.1000.0
Microsoft EdgeHTML 18.18908

And I had to change:

    body: new URLSearchParams(formData),

To:

    body: new URLSearchParams(serializedData ),

But it worked after that.

**Comment by icreatestuff** [comment]
@angrybrad Thanks for taking a look. It's still not working for me though. The javascript response I get is the homepage HTML and not JSON. Interestingly if I fill in all the necessary fields I do get an email through to my inbox but I don't have any JSON data to work with to provide a success message, or any errors if something went wrong or was missing.

**Comment by icreatestuff** [comment]
After many days head scratching I ended up having to add the `Accept: application/json` header to my fetch request like so.

```js
fetch('/', {
    method: 'POST',
    body: new URLSearchParams(serializedData),
    headers: {
        'Accept': 'application/json'
    }
})
.then(response => {
    console.log(response);
    return response.json();
})
.then(data => {
    console.log(data);
});
```
