### ISSUE TITLE
[RFC] Don't allow executable files to be uploaded and attached to emails

### ISSUE THREAD

**Issue by lenvanessen** [craftcms/contact-form#167]
As is stands now, the contact-form plug-in doesn't really validate anything when it comes to the `attachment` file field. The result of that is that anyone can just upload any executable file of their liking and it would be sent to the contact-form recipient. Which might lead to trouble down the way for the employee receiving the contact form e-mail since the source is considered to be trusted.

This would be easily solved by checking the file extension against for instance the already used  `allowedFileExtensions` config option.

I'd be more than happy to make a PR

**Comment by angrybrad** [comment]
@lenvanessen PRs are always welcome!

**Comment by lenvanessen** [comment]
@angrybrad coolio, done

**Comment by lenvanessen** [comment]
@angrybrad don't mean to push the envelope, but when would you have time to review the PR, merge and tag a new version? 

I need the fix applied for a project that's going live soon, otherwise i'll implement it within the `BEFORE_SEND_EVENT` for this specific project.

**Comment by angrybrad** [comment]
@lenvanessen just released https://github.com/craftcms/contact-form/releases/tag/2.2.5 with this in it
