### ISSUE TITLE
Sending emails with attachments fails

### ISSUE THREAD

**Issue by MarioSamison** [craftcms/contact-form#171]
I don't really know if it's a plugin related issue, but if I add an attachment to the email. The email won't send, whereas if I omit the attachment, the e-mail will successfully be sent. Can't seem to find any logs about this.
I'm using craft inside a Docker container.
Where should I look?
Could this issue be related to the SMTP-server?

**Comment by brandonkelly** [comment]
Can you post the code you are using to send the email with the attachment?
