### ISSUE TITLE
Contact form sending homepage instead of form content

### ISSUE THREAD

**Issue by ptag2018** [craftcms/contact-form#183]
I'm pretty new to Craft, I have done 3 websites so far using this CMS and I like it.

It's just now happens on https://gb-skip-hire.rsstech.co.uk/contact , when you submit the contact form, the mail that I receive with the response is full with a web page, not with the text that it has to be.

What I am missing?

Thanks
Paul
![Screenshot 2020-01-08 at 11 46 11](https://user-images.githubusercontent.com/48797084/71975923-0a7ab900-320d-11ea-84c1-f4a921b4844f.png)

**Comment by michellekb** [comment]
Hi @ptag2018 , is it possible you have the Contact Form Extensions plugin installed, with its "Overwrite the e-mail template" setting enabled but no template set? This has caused the behavior you describe for me.

**Comment by ptag2018** [comment]
Hi @michellekb! Yep, you're right, that's the issue. Silly me, how have I missed that? Thanks for help!

**Comment by Friksel** [comment]
Hi @ptag2018 , If you are still wondering about this after these months: are you perhaps using Ajax to send the form? In that case make sure you're using `'application/json'` to both send and accept the form.
