### ISSUE TITLE
Please use Reply-To header instead of From header (quick/easy fix)

### ISSUE THREAD

**Issue by jakepm** [craftcms/contact-form#184]
This plugin actually sets the FROM header in the notification email, to the email address provided by the user. While I presume that this is to allow the recipient to reply directly to the notification email, I really think that the REPLY-TO header should be used instead.

The web server handling the outbound notification email, will almost-always be unauthorised to send mail FROM the unknown emails, being provided by end users. Thus, email clients will see that the email came from an unauthorised server for the given email domain, and will likely flag the email as spam or at least show an unwanted spoof warning.

If there is another reason for using the FROM header, please at least add an option to use the REPLY-TO header instead. I'd also vote for the FROM header to inherit values from the Craft email config (System Email Address & Sender Name).

**Comment by jakepm** [comment]
Lines 38 and 39 in /src/controllers/SendController.php

**Comment by RickKukiela** [comment]
I do not experience this behavior:
`Date: Thu, 13 Feb 2020 12:53:00 -0800
Subject: New message from Acl
From: On behalf of ContactFormFromName <system-email@domain.com>
Reply-To: ContactFormFromName <user-email@domain.com>
To: SystemRecipient@domain.com`

Exactly how it should be...

**Comment by jakepm** [comment]
This must have been a mistake on my part then, apologies for the distraction.
