### ISSUE TITLE
Error(s) in ajax example

### ISSUE THREAD

**Issue by stefanmf** [craftcms/contact-form#201]
Just want to note an error in the ajax example:
in the line `// e.g. response.error.fromName => ['From Name is required']`
the variable is actually `response.errors.fromName`

Also, shouldn't the post url be `url: '/contact-form/send',` instead of just `url: '/',`?

**Comment by jamiematrix** [comment]
I found the errors variable too. 

With the URL, you can still use `<input type="hidden" name="action" value="contact-form/send">` in the form and it'll submit OK - at least it does for me

**Comment by angrybrad** [comment]
Thanks! Fixed in https://github.com/craftcms/contact-form/commit/27eb92312a847f844c53e403d9bd6ddacdbf8f9f
