### ISSUE TITLE
Enquiries are not being save in database

### ISSUE THREAD

**Issue by rosede** [craftcms/contact-form#203]
Hi!  I was wondering how can I get all the leads/enquiries from the past 2 months.
I've downloaded the craft's database to see if  enquiries are being saved, but apparently they're not.

Please advise how to get them. Thanks!

**Comment by angrybrad** [comment]
This plugin doesn't support saving the submissions to the database. A 3rd party plugin has added support for that if you want to try it, though: https://plugins.craftcms.com/contact-form-extensions
