### ISSUE TITLE
Typo in example code results in no validation errors displaying, and no field values re-populating

### ISSUE THREAD

**Issue by realjoshharrison** [craftcms/contact-form#220]
### Description

The example code in the readme includes the line:

    {% set message = message ?? null %}

I couldn't get this to work displaying errors or repopulating field values using the example code. I'm no expert but dug around in the source a bit and tried some stuff, and found this works:

    {% set message = submission ?? null %}

### Steps to reproduce

1. Copy example code
2. Fill in a couple of fields but make sure it won't validate (e.g. leave 'message' blank)
3. Send
4. Errors do not display and any fields you filled in do not maintain their values

### Additional info

- Craft version: 4.0.1
- PHP version: 8.0.8
- Database driver & version: MySQL 5.7.34
- Plugins & versions: Redactor 3.0.0; Contact Form 3.0.0; Contact Form Honeypot 2.0.0

**Comment by realjoshharrison** [comment]
First ever PR! Hope it's all ok?

**Comment by angrybrad** [comment]
You did great!!! Thank you.
