### ISSUE TITLE
Success key and value not being returned in AJAX submission response

### ISSUE THREAD

**Issue by zizther** [craftcms/contact-form#222]
### Description

In this plugin's version 2 for Craft 3 the AJAX response contained the key success which could be tested in the `response` via `if (response.success) { ... }`, this is still present in the docs for v3 for Craft 4, however on submission `reponse.success` returns `undefined` as it does not exist.

### Steps to reproduce

1. Create a form
2. Setup AJAX (as per the docs)
3. Submit the form
4. Get the error

### Additional info

- Craft version: 4.0.2
- PHP version: 8.1
- Contact form plugin version: 3.0.0

**Comment by i-just** [comment]
Hi, thanks for reaching out. This is an intentional change in Craft 4. The documentation was updated shortly after you raised this issue.

**Comment by thisisjamessmith** [comment]
Would be good if the docs had a note on specific breaking changes required on upgrading from Craft 3 to 4 with this in it, this took a while to track down.
