### ISSUE TITLE
Breaking change missing from the changelog

### ISSUE THREAD

**Issue by MoritzLost** [craftcms/contact-form#224]
### Description

I just found out the unpleasant way that the 3.0.0 release includes a change to the route parameter created for a submission with errors. As per the updated readme, the submission is now available to the contact form template as `submission` instead of `message`. This is a breaking change, as every contact form template using the module will need to be updated to accomodate.

This breaking change is missing in the changelog for the 3.0.0 release and should be added there immediately, to prevent lots of broken forms and frustration for other developers.

### Additional info

- Craft version: 4.0.3
- PHP version: 8.1

**Comment by brandonkelly** [comment]
Doh, sorry about that. Just updated the changelog.

**Comment by MoritzLost** [comment]
Thanks @brandonkelly!
