### ISSUE TITLE
Craft 4: fromName field now required to be in the field list

### ISSUE THREAD

**Issue by MetaDevelopment** [craftcms/contact-form#228]
### Description
As from Craft 4, if the fromName field is not in the form, submitting the form leads to an error: 

> Symfony\Component\Mime\Address::__construct(): Argument #2 ($name) must be of type string, null given, called in .../vendor/yiisoft/yii2-symfonymailer/src/Message.php on line 368

As far as I can see the documentation does not mention that this field is 'required' (not really required, but it needs to be in the field list to work). 

### Steps to reproduce

1. Install Contact Form plugin on a Craft CMS 4 instance 
2. Use the example form code, but remove the fromName field 
3. Complete and submit the form 

### Additional info

- Craft version: 4.1.2 
- PHP version: 8.1.5

**Comment by mightyfineyall** [comment]
Seconding this, just ran into it.

`<input aria-label="Name" required="required" id="from-name" class="input--half" type="text" placeholder="Name" name="fromName" value="{{ message.lastName ?? '' }}">
        {{ message is defined and message ? errorList(message.getErrors('lastName')) }}`

works but 

`<input aria-label="First Name" required="required" id="first-name" class="input--half" type="text" placeholder="First Name" name="message[firstName]" value="{{ message.firstName ?? '' }}">
        {{ message is defined and message ? errorList(message.getErrors('firstName')) }}

        <input aria-label="Last Name" required="required" id="last-name" class="input--half" type="text" placeholder="Last Name" name="message[lastName]" value="{{ message.lastName ?? '' }}">
        {{ message is defined and message ? errorList(message.getErrors('lastName')) }}`

**Comment by kevinmu17** [comment]
My guess is that the new _symphony mailer_ requires the fromName, since Craft CMS 4 it uses this new mailer engine.

**Comment by ammannbe** [comment]
> Same here for this one, a relatively simple temporary fix if it's appropriate, is to simply add in a hidden field with the site name.
> 
> `<input type="hidden" name="fromName" value="{{ siteName }}" />`

It's not necessary to provide a value, you can also have an empty input field:

`<input type="hidden" name="fromName" value="" />`

**Comment by brandonkelly** [comment]
Contact Form 3.0.1 is out with a fix for this!
