### ISSUE TITLE
Contact form changes password confirmation emails

### ISSUE THREAD

**Issue by arentsen** [craftcms/contact-form#252]
### Description
Any emails that are sent out by the system (such as a password reset link) have the correct subject, but the contents of the emails gets overwritten by the contents of the contact confirmation email. I just used the examples from the manual, nothing fancy. Somehow, it seems that this variable {{ emailParts[1]|default|raw }} changes something globally and any email that gets send out uses it. Any help would really be appreciated

I also installed the honeypot plugin.

I found the file Module.php in the modules/email folder with the following contents. Not sure if it should be there:

```
<?php

/*
namespace modules\email;

use Craft;
use yii\base\Module as BaseModule;

/**
 * contact-form module
 *
 * @method static Module getInstance()
 */


class Module extends BaseModule
{
    public function init(): void
    {
        Craft::setAlias('@modules/email', __DIR__);

        // Set the controllerNamespace based on whether this is a console or web request
        if (Craft::$app->request->isConsoleRequest) {
            $this->controllerNamespace = 'modules\\email\\console\\controllers';
        } else {
            $this->controllerNamespace = 'modules\\email\\controllers';
        }

        parent::init();

        // Defer most setup tasks until Craft is fully initialized
        Craft::$app->onInit(function() {
            $this->attachEventHandlers();
            // ...
        });
    }

    private function attachEventHandlers(): void
    {
        // Register event handlers here ...
        // (see https://craftcms.com/docs/4.x/extend/events.html to get started)
    }
}
```

### Steps to reproduce

1.
2.

### Additional info

- Craft version: 4.5.7
- PHP version: 8.0.2
- Database driver & version:
- Plugins & versions: Contact-form plugin 3.0.1

**Comment by arentsen** [comment]
No progress here. I disabled both the Contact Form and Contact Form Extensions plugins, but the "Send activation email" for a new user still gets overwritten by the template that is used for the contact notification email.

**Comment by i-just** [comment]
Hi, thanks for reaching out. As per https://github.com/craftcms/cms/issues/14504 Contact Form Extensions plugin is a 3rd party plugin, so this will have to be looked into from their end.
