### ISSUE TITLE
Cannot use Yii file validator on a single file attachment field

### ISSUE THREAD

**Issue by nstCactus** [craftcms/contact-form#254]
When using the Yii file validator on a single file attachment field, the validator always returns an error indicating that no file was uploaded.

# Steps to reproduce

1. Add a contact form with a single file `attachment` field:

````html
<input type="file" name="attachment" />

````

2. In a module, add a file validation rule on the `attachment` field:

````php
Event::on(Submission::class, Submission::EVENT_DEFINE_RULES, static function(DefineRulesEvent $event): void {
    $event->rules[] = [ 'attachment', 'file', 'maxSize' => 2 * 1024 * 1024 ];
});
````

3. Submit the form with a file

# Expected outcome

The form should be successfully validated and the message sent.

# Actuel outcome

There is a validation issue on the `attachment` field with the following message: `Please upload a file.`

# Environment

- Craft version: 3.9.10
- contact-form plugin version: 2.5.2

# Analysis

In [this line](https://github.com/craftcms/contact-form/blob/bb6ab42e06ff3816cb50c666a41294925e900672/src/controllers/SendController.php#L49), the `$submission->attachment` property is set to an array. The Yii file validator receives this array in its [`validateValue($value)`](https://github.com/yiisoft/yii2/blob/b4045bac5599b439c95a1b4be9466dc5c68d1f0f/framework/validators/FileValidator.php#L271) method. This method checks that its `$value` parameter is an instance of `\yii\web\UploadedFile` which fails because it's actually an array.

**Comment by brandonkelly** [comment]
Contact Form 2.5.3 (Craft 3) and 3.1.0 (Craft 4 and 5) have been released with that change 🎉
