### ISSUE TITLE
Validation on select field

### ISSUE THREAD

**Issue by warrebuysse** [craftcms/contact-form#73]
I have the following select field where I would like to do validation. When the first option is selected (default one) the result is empty and should therefor return an error. There is no information available on this.

1. Is it possible?
2. What is the correct approach?

```html
<div class="form__row">
	<select id="type" name="message[Type]" class="select select--block">
		<option placeholder value="">-- Selecteer type --</option>
		<option value="Trouwen" {% if message.messageFields['Type'] == 'Trouwen' %}selected{% endif %}>Trouwen</option>
		<option value="Festival" {% if message.messageFields['Type'] == 'Festival' %}selected{% endif %}>Festival</option>
		<option value="Bedrijfsevent" {% if message.messageFields['Type'] == 'Bedrijfsevent' %}selected{% endif %}>Bedrijfsevent</option>
		<option value="Ander" {% if message.messageFields['Type'] == 'Ander' %}selected{% endif %}>Ander</option>
	</select>
</div>
```

**Comment by rauwebieten** [comment]
You should look into the afterValidate event I think.
See the README file for an example

**Comment by angrybrad** [comment]
What @rauwebieten said.  Relevant docs here: https://github.com/craftcms/contact-form#the-aftervalidate-event
