### ISSUE TITLE
Showing a success message after submit

### ISSUE THREAD

**Issue by warrebuysse** [craftcms/contact-form#74]
There is no documentation on how to show a success message after a form has been submitted on the same page. I am not looking for the thanks page approach. I would rather to show a notification that the mail has been sent out correctly. How should I tackle this?

**Comment by Artcoholic** [comment]
I would like to know this too.

**Comment by reganlawton** [comment]
@Artcoholic  & @warrebuysse This can be done simply by using the redirect option

```
 <form method="post" action="" accept-charset="UTF-8">
    {{ getCsrfInput() }}
    <input type="hidden" name="redirect" value="{{ craft.request.url }}?sent=1">
    <input type="hidden" name="action" value="contactForm/sendMessage">
</form>
```

Then in your tempalate you check if sent

```
{% if craft.request.param('sent') %}
    <p class="callout success">
        Thank you for your message.
    </p>
{% endif %}
```

**Comment by NathanHeffley** [comment]
I dug around in the source code a little bit and found out how you can access that flash message that you set in the settings page. To grab the value, you just need to use `craft.app.session.getFlash('notice')` to output the message.

What I did is add a div that gets absolutely positioned and only shows up if there is a notice.

**Comment by NathanHeffley** [comment]
Just put in pull request #96 to add a small example about using the value of the flash message setting.

**Comment by brandonkelly** [comment]
Thanks @NathanHeffley! Just merged the PR.
