### ISSUE TITLE
Hooks don't actually allow you to modify the email content

### ISSUE THREAD

**Issue by bryantAXS** [craftcms/contact-form#75]
The hooks provided for the beforeSend and compileMessage events don't actually allow you to update the contents of the email. I copied them directly from the readme file and it's still sending out the email same as if no hook was called.

It seems like the methods are either called to early, or potentially the data passed in needs to be provided by reference.

**Comment by takobell** [comment]
This should be resolved if you pull the latest commit down. Be sure to check out the updated [README](https://github.com/craftcms/contact-form/tree/v1#the-contactformbeforemessagecompile-event) example for guidance.
