### ISSUE TITLE
contactForm.beforeMessageCompile not working ?

### ISSUE THREAD

**Issue by Chrisedmo** [craftcms/contact-form#80]
I'm getting the following error when creating a plug in with the example code for the contactForm.beforeMessageCompile event:

```
Internal Server Error
Undefined index: message
```

All I want to do is add in the from Email address and the name in the message body.  I haven't even changed anything from the example on the Read Me.

Any ideas?

**Comment by takobell** [comment]
Can you enable devMode and share the whole stack trace?

**Comment by Chrisedmo** [comment]
@takobell Thanks for the reply: here is the error message in the stack:

```
[Error] [12:56:12.809][error][php]
Undefined index: message (/Users/chrismousdale/Documents/Sites/websitename/private_html/craft/plugins/contactformextras/ContactFormExtrasPlugin.php:29)
Stack trace:
#0 /Users/chrismousdale/Documents/Sites/websitename/private_html/craft/plugins/contactform/services/ContactFormService.php(99): Craft\ContactFormService->raiseEvent()
#1 /Users/chrismousdale/Documents/Sites/websitename/private_html/craft/plugins/contactform/controllers/ContactFormController.php(55): Craft\ContactFormService->onBeforeMessageCompile()
#2 /Users/chrismousdale/Documents/Sites/websitename/private_html/craft/app/framework/web/actions/CInlineAction.php(49): Craft\ContactFormController->actionSendMessage()
#3 /Users/chrismousdale/Documents/Sites/websitename/private_html/craft/app/framework/web/CController.php(308): CInlineAction->runWithParams()
#4 /Users/chrismousdale/Documents/Sites/websitename/private_html/craft/app/framework/web/CController.php(286): Craft\ContactFormController->runAction()
#5 /Users/chrismousdale/Documents/Sites/websitename/private_html/craft/app/framework/web/CController.php(265): Craft\ContactFormController->runActionWithFilters()
#6 /Users/chrismousdale/Documents/Sites/websitename/private_html/craft/app/framework/web/CWebApplication.php(282): Craft\ContactFormController->run()
#7 /Users/chrismousdale/Documents/Sites/websitename/private_html/craft/app/etc/web/WebApp.php(817): Craft\WebApp->runController()
#8 /Users/chrismousdale/Documents/Sites/websitename/private_html/craft/app/etc/web/WebApp.php(287): Craft\WebApp->_processActionRequest()
#9 /Users/chrismousdale/Documents/Sites/websitename/private_html/craft/app/framework/base/CApplication.php(185): Craft\WebApp->processRequest()
#10 /Users/chrismousdale/Documents/Sites/websitename/private_html/craft/app/index.php(62): Craft\WebApp->run()
#11 /Users/chrismousdale/Documents/Sites/websitename/public_html/index.php(19): require_once()
#12 /Users/chrismousdale/.composer/vendor/laravel/valet/server.php(133): require()
REQUEST_URI=/contact
in /Users/chrismousdale/Documents/Sites/websitename/private_html/craft/app/etc/web/WebApp.php (687)
in /Users/chrismousdale/Documents/Sites/websitename/private_html/craft/plugins/contactformextras/ContactFormExtrasPlugin.php (29)
in /Users/chrismousdale/Documents/Sites/websitename/private_html/craft/plugins/contactform/services/ContactFormService.php (99)
	Global Code (contact:615)
```

**Comment by tidy** [comment]
I'm also having this issue (no internal server error, just the undefined index message).

If I comment out the 3 variable setting lines  from the readme example and then just have the 2 lines setting $events->params['message'] and params['htmlMessage'] to static text without including $message anywhere, the error goes but the email text does not change. 

So it's as if those parameters are not actually controlling the message content and that's why they do not exist?

**Comment by brandonkelly** [comment]
Looks like this was just a documentation bug. Fixed the code sample: https://github.com/craftcms/contact-form/tree/v1#the-contactformbeforemessagecompile-event

**Comment by takobell** [comment]
@Chrisedmo Also just noticed the error you're getting is coming from the `ContactFormExtrasPlugin` you have installed, not from the Craft ContactForm plugin.

**Comment by takobell** [comment]
@tidy pull the latest top of tree commit and try again.  There's also updated documentation using the [onBeforeMessageCompile](https://github.com/craftcms/contact-form/tree/v1#the-contactformbeforemessagecompile-event) event you'll want to look at.

**Comment by tidy** [comment]
Many thanks Brad - works fine now

**Comment by Chrisedmo** [comment]
@takobell That's because I was trying to add to the HTML email body, using a home made plugin as per your example listed under: `contactForm.beforeMessageCompile` in the README.md. But I will try updating the code as per Brandon's message above. Thanks.
