### ISSUE TITLE
Multi-environment config doesn't work for multi-site

### ISSUE THREAD

**Issue by Rias500** [craftcms/contact-form#81]
If you want to for example set a different toEmail for each locale, the plugin settings give an error:

```
return [
    '*' => [
        'toEmail' => [
            'siteEN' => 'siteEN@example.com',
            'siteNL' => 'siteNL@example.com'
        ]
    ]
];
```

The error is an `array to string conversion` error, which is caused because the settings template tries to get the `toEmail` key but doesn't handle the locales

**Comment by brandonkelly** [comment]
The `toEmail` setting doesn't currently support per-locale/site values. Here’s a way you could pull it off, though: https://github.com/craftcms/contact-form#dynamically-adding-email-recipients
