### ISSUE TITLE
Composer Update from 2.0.1 to 2.0.2 throws exception

### ISSUE THREAD

**Issue by hiasl** [craftcms/contact-form#86]
A composer update from 2.0.1 to 2.0.2 threw that exception for me:
  - Removing craftcms/contact-form (2.0.1)
  - Installing craftcms/contact-form (2.0.2)
    Downloading: 100%         

  [ErrorException]                                                                                                                                                                                           
  Argument 1 passed to craft\composer\Installer::unregisterPlugin() must be an instance of craft\composer\string, string given, called in /Users/hiasl/Documents/Projekte/cardsys-website2017/app/vendor/cr  
  aftcms/plugin-installer/src/Installer.php on line 341 and defined  

**Also Craft 3 itself was updated:**
  - Removing craftcms/cms (3.0.0-beta.19)
  - Installing craftcms/cms (3.0.0-beta.21)
    Downloading: 100%         

**Side Infos:**
PHP version	7.0.19-1
Database driver & version	MySQL 5.5.5-10.1.23-MariaDB-9+deb9u1
Image driver & version	Imagick 3.4.3RC2, ImageMagick 6.9.7-4
Craft edition & version	Craft Pro 3.0.0-beta.19
Yii version	2.0.11.2
Twig version	2.3.2
Guzzle version	6.2.1
Imagine version	0.7-dev

**Comment by brandonkelly** [comment]
This should be fixed. Run this:

    composer update craftcms/plugin-installer

then

    composer update
