### ISSUE TITLE
Custom recipient not working

### ISSUE THREAD

**Issue by achord** [craftcms/contact-form#87]
When I add the suggested config to /craft/config/contactform.php, I get a white screen.  THe log isn't helpful either:
E.g.

```
<?php

    return [
        'toEmail' => Craft::$app->request->getValidatedBodyParam('toEmail')
    ];
```

**Comment by takobell** [comment]
Are you using Contact Form 1 or 2?  Contact Form 2 is for Craft 3 and Contact Form is for Craft 2. Your example is using Craft 3 syntax.

**Comment by achord** [comment]
Craft 2.6.2986, Contact form: 1.9.0

**Comment by takobell** [comment]
Use the syntax from the v1 docs: "repositories": [
    {
      "type": "composer",
      "url": "https://asset-packagist.org"
    }
  ]
