### ISSUE TITLE
Can no longer access individual message fields values via message.messageFields

### ISSUE THREAD

**Issue by d13creative** [craftcms/contact-form#88]
The latest version appears to have broken this functionality. I get this error if the form fails validation:

> Impossible to access a key ("Telephone") on a null variable

Here's my template code:

```twig
<input type="text" id="telephone" name="message[Telephone]" value="{% if message is defined %}{{ message.messageFields['Telephone'] }}{% endif %}" class="form-control input-lg">
```

**Comment by brandonkelly** [comment]
Guessing this has something to do with #84 /@carlcs

**Comment by takobell** [comment]
I'm not able to reproduce this on the latest 1.9.0 (https://github.com/craftcms/contact-form/archive/1.9.0.zip). Can you verify you're on that verison?

**Comment by d13creative** [comment]
Yes, version 1.9.0, I can send the site via the CP to you if you like.

**Comment by takobell** [comment]
@d13creative Just your contact form template should be enough. Can send to support@craftcms.com
