### ISSUE TITLE
Unable to put CSS inside htmlMessage when overriding the look and feel of the email

### ISSUE THREAD

**Issue by RickKukiela** [craftcms/contact-form#90]
I'm sending a fully valid HTML document inside `$event->htmlMessage` from the onBeforeMessageCompile event and its working except for the fact that all of my `{` and `}` characters are getting changed to `&lbrace;` and `&rbrace;`.

This is a hard coded "feature" and I'm not sure what to do about it other than hack the core files and never update it. I would do a PR but I'm not even sure how I would go about fixing this aside from removing this line, but if you really need that code there Idk what to tell you. Its definitely a problem though and Im not sure how this hasn't come up fro anyone else yet...

Here is the line causing the problem: 
 https://github.com/craftcms/contact-form/blob/77bed0bc54fdfe69c401b3bd83c766f92112f92c/contactform/services/ContactFormService.php#L48

Also I'm using V1 on craft 2.x

Any ideas on how to work around this?

Just to be clear, in my htmlMessage, in the compiled email,

` #element { color: blue; }`

becomes:

`#element &lbrace; color:blue; &rbrace;`

Which is obviously invalid.

**Comment by SublymeRick** [comment]
Well I just hacked up core for now, let me know if there is something I'm missing.

**Comment by brandonkelly** [comment]
Fixed – thanks!
