### ISSUE TITLE
Dynamically adding email recipients

### ISSUE THREAD

**Issue by jefffulton** [craftcms/contact-form#93]
Is it possible to pull this from an entry field on the page?

```twig
<input type="hidden" name="toEmail" value="{{ entry.groupLeaderEmail|hash }}">
````

I've done everything according to the README. It looks like its rendering properly in the source, but the form doesn't work.

**Comment by jefffulton** [comment]
Also, when I add the elipses to contactform.php, it crashes my site...
`<?php
    namespace Craft;

    $toEmail = craft()->request->getPost('toEmail');
    $toEmail = craft()->security->validateData($toEmail);

    return array(
        'toEmail' => ($toEmail ?: null),
        ...
    );`

I get this error:
> Internal Server Error
> 
> syntax error, unexpected '...' (T_ELLIPSIS), expecting ')'
> >

**Comment by brandonkelly** [comment]
That `...` should have been `// ...`. It’s not actually necessary; just a placeholder for "any other config settings you want to set". Remove the line (or add `//`) and your `toEmail` input should start working.

**Comment by jefffulton** [comment]
I followed the instructions and created contactform.php, and it still isn't working. I checked spam folders just in case.

I thought it could be my entry field, but...
`<input type="hidden" name="toEmail" value="{{ entry.groupLeaderEmail|hash }}">`
is rendering in the source code the same as
`<input type="hidden" name="toEmail" value="{{ 'jeff@fultondesign.net'|hash }}">`

**Comment by brandonkelly** [comment]
Can you confirm two things for me?

- You’re using Craft 2 (not Craft 3)
- You’re using Contact Form >= 2.6

**Comment by jefffulton** [comment]
I think it's the current build: 2.6.2990

**Comment by takobell** [comment]
@jefffulton Do _any_ emails go through in Craft?  You can test under Settings->Email in the Craft Control Panel.  Here's an article for debugging email errors as well as email delivery issues in Craft: https://craftcms.com/support/troubleshooting-email-errors

**Comment by jefffulton** [comment]
@takobell the test said all is working.

**Comment by takobell** [comment]
And you actually received the test email?

**Comment by jefffulton** [comment]
@takobell no. I did not.

**Comment by takobell** [comment]
I'd read through https://craftcms.com/support/troubleshooting-email-errors#dealing-with-email-delivery-issues

Particularly the last bullet point.

**Comment by jefffulton** [comment]
@takobell and @brandonkelly I resolved the issue using Postmark instead of PHP Mail.

`<input type="hidden" name="toEmail" value="{{ entry.groupLeaderEmail|hash }}">` is working perfectly now.

**Comment by brandonkelly** [comment]
Glad to hear you got it sorted! Strange that PHP Mail wasn't respecting the custom toEmail, but there are plenty of other reasons you should switch off of that anyway :)
