### ISSUE TITLE
Cannot install this update without composer

### ISSUE THREAD

**Issue by cavidano** [craftcms/contact-form#99]
Hello, 

I love this plug-in and have used it on several occasions. I am wondering why it cannot be installed without Composer, something I have had little luck getting to recognize your install command. The previous version of the contact form could simply be downloaded and installed by placing the folder in Craft's plug-in directory. 

The client needs the ability to see the user-inputted email address. Any guidance is greatly appreciated.

Best, 
Carl

**Comment by brandonkelly** [comment]
All Craft 3 plugins must be installed with Composer (at least during the Beta). Are you looking for the Craft 2 version? You can get that here: https://github.com/craftcms/contact-form/tree/v1
